### PR TITLE
Update README.md to reflect fork.

### PR DESCRIPTION
**Pull request by spinza**

### CODE REVIEW

**Comment by spinza** [comment]
Sorry wrong project :)

**Comment by sque** [comment]
Still, good news that ppl are forking :)

**Comment by spinza** [comment]
Are you no longer accepting PRs?  Is there a reason?

**Comment by sque** [comment]
It is only problem of non-existing time. I tried to review an MR just an hour ago but I need a lot of time to refresh my memory and I finally postponed it. That is why I am happy ppl are forking, if you build a nice community we can merge back and take over

**Comment by sque** [comment]
I mean that you take over the upstream

**Pull request closed without merging**
